### ISSUE TITLE
Idea: Improve UX with ssh:// links

### ISSUE THREAD

**Issue by Gaelan** [duncankl/ssh-mars#1]
On OSX, `ssh://` links work, though the window closes before I can copy the URL. If we added a "press enter when done" prompt on the server as well as a `ssh://` link on the home page, the usability could improve quite a bit.

**Comment by duncankl** [comment]
Wow, I wasn't aware OSX had that feature! If it works like I'm imagining it, then any website could open an `ssh://` link in the background and learn the user's public key. Seems like a privacy issue.

Thanks for the tip, I'll have to check it out.

**Comment by duncankl** [comment]
(I guess you also have to type "yes" to confirm the fingerprint, so perhaps this isn't a privacy issue)

**Comment by duncankl** [comment]
Finally got my hands on a Mac to try this out. [Here's a video of the result](https://vtllf.org/blog/ssh-web-sign-in/screencast-ssh-url-handler.mp4).

(Apologies for the watermark, is there no good free screencasting software on OSX?)

The code is sitting in the `url-handler` branch, but I'm probably going to leave it at that. Also looks like a bunch of UI stuff is broken on Safari, oops.

**Comment by Gaelan** [comment]
Quicktime (built in) can screencast. File > New Screen Recording

**Comment by duncankl** [comment]
Good point. I couldn't figure out how to get Quicktime to record just a portion of the screen, but I guess iMovie or ffmpeg could crop it afterwards.
