### ISSUE TITLE
Instructions are completely useless on Windows

### ISSUE THREAD

**Issue by interfect** [duncankl/ssh-mars#2]
Windows doesn't ship with SSH, so the commands that are given on the "how" page are no help. Worse, the page gives no indication of this, leaving windows users scratching their heads.

The "how" page should walk Windows users through installing SSH.

**Comment by duncankl** [comment]
Sorry about that! I'd have to do more research into which SSH clients are good on Windows first. Do you know of any guides that could be linked to in the meantime? [GitHub's is not bad](https://help.github.com/articles/generating-ssh-keys/#platform-windows) but it is also very GitHub specific.
