### ISSUE TITLE
zbase32-go dependency

### ISSUE THREAD

**Issue by eirmag** [duncankl/ssh-mars#3]
Hi,
I had issues during retrieval of the ssh-mars project, as go dependency "github.com/duncankl/zbase32" was not found (dependency indicated in cmd.go).
Instead of modifying your code, I did manually install the correct package (zbase32-go), and rename it to the expected package name (zbase32)

Therefore:
go get github.com/duncankl/ssh-mars
go get github.com/duncankl/zbase32-go
mv $GOPATH/src/github.com/duncankl/zbase32{-go,}
etc.

Let me know if I'm doing something wrong,
Best regards,
Gabriel

**Comment by duncankl** [comment]
Oops, looks like I uploaded zbase32 to GitHub under the wrong name. I've renamed that repo so hopefully Go will find it now. Thanks for figuring out what was going wrong and reporting it!
